let storeItemsData = [
  { id: "clothingItem1", 
  name: "Silk Dress",
price: 50,  
img: "pictures/off-shoulder-dress.jpg",} ,
{id: "clothingItem2", 
name: "Sequin Dress",
price: 99, 
img: "pictures/sequin-dress.jpg",} ,
{id: "clothingItem3", 
name: "Casual Dress",
price: 70,
img: "pictures/leather-jacket.jpg",} ,
{ id: "clothingItem4", 
name: "Summer Dress",
price: 58, 
img: "pictures/white-dress.jpg",} ,
{ id: "clothingItem5", 
name: "Spring Dress",
price: 40, 
img: "pictures/casual-dress.jpg",} ,
{ id: "clothingItem6", 
name: "Wedding Dress",
price: 570,
img: "pictures/wedding.jpg",} ,
{id: "clothingItem7", 
name: "Formal Dress",
price: 150, 
img:"pictures/bridesmaid.jpg",} ,
{id: "clothingItem8", 
name: "Chiffon Dress",
price: 90, 
img:"pictures/red-oneshoulder.jpg",}

];
